### ISSUE TITLE
Roman emperors mapping: xsd:dateTime problem

### ISSUE THREAD

**Issue by pietercolpaert** [opendatasoft/ontology-mapping-chatbot#4]
A bug concerning this dataset: https://public.opendatasoft.com/api/tpf/roman-emperors/

There is a typo in the datatype for xsd:dateTimes. It has `xsd:datetime`, but this URI does not exist. It must be corrected to `xsd:dateTime` in order for the demo queries in the documentation of Open Data Soft’s RDF to work.

**Comment by vbarbaresi** [comment]
Good catch, the camelCase was indeed missing. We just deployed a fix.
Thanks!

**Comment by pietercolpaert** [comment]
Thanks for the swift response!
